version: '3.4'

services:
  ekklesia.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Data Source=/data/db/ekklesia.sqlite"
      - RABBITMQ_SERVER=rabbitmq
    ports:
      - "80"
    networks:
      - default
      - ekklesia-dev
    volumes:
      - db:/data/db
    
volumes:
  db:

networks:
  ekklesia-dev:
    external: true